spring:
  datasource:
    url: jdbc:h2:mem:product_domain_db
    username: productmanager
    password: productmanager
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop

server:
  port: 8081
